version: '3.8'

services:
  cockroachdb:
    image: cockroachdb/cockroach:v23.2.3
    container_name: cockroachdb-wallets
    ports:
      - "26257:26257"
      - "8081:8081"
    volumes:
      - cockroach-data:/cockroach/cockroach-data
      - ./init:/docker-entrypoint-initdb.d
    command: start-single-node --insecure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    environment:
      - COCKROACH_CHANNEL=stable
      - COCKROACH_DATABASE=wallet_db

  redis:
    image: redis:7-alpine
    container_name: redis-wallets
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  cockroach-data:
    driver: local
  redis-data:
    driver: local
