version: '3.8'

services:
  cockroachdb:
    image: cockroachdb/cockroach:v23.2.3
    container_name: cockroachdb-wallets
    ports:
      - "26257:26257"
      - "8081:8081"
    volumes:
      - cockroach-data:/cockroach/cockroach-data
      - ./init:/docker-entrypoint-initdb.d
    command: start-single-node --insecure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    environment:
      - COCKROACH_CHANNEL=stable
      - COCKROACH_DATABASE=wallet_db

volumes:
  cockroach-data:
    driver: local